---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doks-cluster-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/hnatekmarorg/hetzner-k8s.git
    targetRevision: HEAD
    path: charts/doks-cluster
    helm:
      releaseName: doks-cluster-production
      valuesObject:
        cluster:
          name: "production-cluster"
          region: "fra1"
          version: "1.35.1-do.1"
          nodePool:
            name: "default"
            size: "s-2vcpu-2gb"
            nodeCount: 1
          providerConfigRef:
            name: "digitalocean"
          writeConnectionSecretToRef:
            name: "production-cluster"
            namespace: "crossplane-system"
          argocd:
            enabled: true
            project: "default"
            repoURL: "https://github.com/hnatekmarorg/hetzner-k8s.git"
            targetRevision: "HEAD"
            namespace: "default"
            syncPolicy:
              selfHeal: true
              prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: doks-cluster-production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
