apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baikal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/hnatekmarorg/hetzner-k8s.git
    targetRevision: main
    path: charts/baikal
    helm:
      releaseName: baikal
  destination:
    server: https://kubernetes.default.svc
    namespace: baikal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m