{{- $cluster := .Values.cluster -}}
{{- $clusterName := $cluster.name | default .Release.Name -}}
{{- $argocd := .Values.argocd -}}
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: {{ $clusterName }}-base-apps
spec:
  forProvider:
    # ArgoCD Application that bootstraps the cluster with foundational services
    manifest:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: base
        namespace: argocd
        annotations:
          argocd.argoproj.io/sync-wave: "2"
      spec:
        project: default
        destination:
          server: https://kubernetes.default.svc
          namespace: argocd
        source:
          repoURL: {{ $argocd.repoUrl }}
          targetRevision: {{ $argocd.targetRevision | quote }}
          path: {{ $argocd.path }}
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
            allowEmpty: true
          syncOptions:
            - CreateNamespace=true
            - PrunePropagationPolicy=foreground
            - PruneLast=true
          retry:
            limit: -1
            backoff:
              duration: 5s
              factor: 2
              maxDuration: 3m
  providerConfigRef:
    name: {{ $clusterName }}-kubernetes
