apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-sso
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes
    kind: ClusterSecretStore
  target:
    name: argocd-sso
    creationPolicy: Owner
  data:
    - secretKey: clientID
      remoteRef:
        key: argocd-bootstrap-hnatekmar-xyz
        namespace: crossplane-system
        property: attribute.client_id
    - secretKey: secretKey
      remoteRef:
        key: argocd-bootstrap-hnatekmar-xyz
        namespace: crossplane-system
        property: attribute.client_secret
