apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
  namespace: keycloak
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: local
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-creds
  data:
    - secretKey: username
      remoteRef:
        key: /admin/keycloak
        property: username
    - secretKey: password
      remoteRef:
        key: /admin/keycloak
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-creds
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Apply before Keycloak Helm chart
spec:
  refreshInterval: "15s"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-db-password
  target:
    name: keycloak-db-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          app.kubernetes.io/name: keycloak
          app.kubernetes.io/component: database
      data:
        username: "keycloak"
        password: "{{ .password }}"
        postgres-password: "{{ .password }}"
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: keycloak-db-password
  namespace: keycloak
spec:
  length: 32
  digits: 8
  symbols: 4
  noUpper: false
  allowRepeat: false
