apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
  namespace: keycloak
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: local
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-creds
  data:
    - secretKey: username
      remoteRef:
        key: /admin/keycloak
        property: username
    - secretKey: password
      remoteRef:
        key: /admin/keycloak
        property: password
