apiVersion: jwt.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: sso-hnatekmarorg-admin
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: bao-hnatekmar-xyz
  forProvider:
    backendRef:
      name: sso
    userClaim: email
    allowedRedirectUris:
      - https://bao.hnatekmar.xyz/ui/vault/auth/oidc/oidc/callback
      - http://localhost:8250/oidc/callback
    roleName: sso-hnatekmarorg-admin
    roleType: oidc
    groupsClaim: groups
    boundClaims:
      groups: "hnatekmarorg-admin"
    tokenPolicies:
      - hnatekmarorg-admin
    # Token TTL limits for user tokens
    tokenTtl: 3600
    tokenMaxTtl: 14400
    tokenType: "service"
