apiVersion: v1
kind: Service
metadata:
  name: thingsboard
  namespace: thingsboard
  labels:
    app.kubernetes.io/name: thingsboard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: thingsboard
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: thingsboard-mqtt
  namespace: thingsboard
  labels:
    app.kubernetes.io/name: thingsboard
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: thingsboard
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: mqtt-tls
      port: 8883
      targetPort: 8883
    - name: coap
      port: 5683
      targetPort: 5683
      protocol: UDP
