---
# ArgoCD SSO Secret
# Contains Keycloak client credentials for OIDC authentication
apiVersion: v1
kind: Secret
metadata:
  name: argocd-sso
  namespace: argocd
type: Opaque
stringData:
  clientID: argocd-bootstrap-hnatekmar-xyz
  secretKey: 4ykWa1ZesFfFB5N10uY2EE9N5mia1FIb
