apiVersion: vault.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: hnatekmarorg-admin
  namespace: crossplane-system
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: bao-hnatekmar-xyz
  forProvider:
    name: hnatekmarorg-admin
    policy: |
      path "hnatekmarorg-ssh/*" {
        capabilities = ["read", "list"]
      }
      path "hnatekmarorg-ssh/sign/*" {
        capabilities = ["create", "update"]
      }
      path "hnatekmarorg-ssh/roles/*" {
        capabilities = ["read", "list"]
      }
      path "hnatekmarorg-ssh/config/ca" {
        capabilities = ["read"]
      }
      path "hnatekmarorg-ssh/sign/*" {
        capabilities = ["create", "update"]
      }
