apiVersion: vault.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: hnatekmarorg
  namespace: crossplane-system
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: bao-hnatekmar-xyz
  forProvider:
    name: hnatekmarorg
    policy: |
      path "hnatekmarorg/data/*" {
        capabilities = ["read", "list"]
      }
      path "hnatekmarorg/metadata/*" {
        capabilities = ["read", "list"]
      }
      path "hnatekmarorg-ssh/sign/user" {
        capabilities = ["create", "update"]
      }
