apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bao-cert
  namespace: openbao-system
spec:
  secretName: bao-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - bao.hnatekmar.xyz
