apiVersion: v1
kind: Namespace
metadata:
  name: openbao-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/ignore-differences: |
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        name: openbao-agent-injector-cfg
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/0/sideEffects
spec:
  project: default
  sources:
    - chart: openbao
      repoURL: https://openbao.github.io/openbao-helm
      targetRevision: 0.22.0
      helm:
        releaseName: openbao
        valueFiles:
          - $repo/argocd/openbao/values.yaml
    - repoURL: 'https://github.com/hnatekmarorg/hetzner-k8s.git'
      targetRevision: main
      ref: repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openbao-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
