apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "baikal.fullname" . }}
  labels:
    {{- include "baikal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "baikal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "baikal.labels" . | nindent 8 }}
    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init-dirs
          image: busybox:1.36
          command: ["/bin/sh", "-c", "mkdir -p /data/Specific /data/config"]
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/www/baikal/Specific
              subPath: Specific
            - name: data
              mountPath: /var/www/baikal/config
              subPath: config
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "baikal.fullname" . }}-data
