apiVersion: v1
kind: Service
metadata:
  name: {{ include "baikal.fullname" . }}
  labels:
    {{- include "baikal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "baikal.selectorLabels" . | nindent 4 }}
