---
# Keycloak Group for algovectra users
# Users added to this group will have access to algovectra resources
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: algovectra
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  providerConfigRef:
    name: sso-hnatekmar-xyz
  forProvider:
    name: algovectra
    realmId: master
