---
# Keycloak Group for hnatekmarorg Administrators
# Users added to this group can manage SSH backend and sign any certificates
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: hnatekmarorg-admin
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  providerConfigRef:
    name: sso-hnatekmar-xyz
  forProvider:
    name: hnatekmarorg-admin
    realmId: master
