apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-init
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    directory:
      recurse: true
    repoURL: https://github.com/hnatekmarorg/hetzner-k8s.git
    targetRevision: HEAD
    path: crossplane/init
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    directory:
      recurse: true
    repoURL: https://github.com/hnatekmarorg/hetzner-k8s.git
    targetRevision: HEAD
    path: crossplane/config
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/data
  source:
    directory:
      recurse: true
    repoURL: https://github.com/hnatekmarorg/hetzner-k8s.git
    targetRevision: HEAD
    path: crossplane/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
